language: ruby
rvm:
- 2.2.0
before_script:
- cp config/database.sample.yml config/database.yml
- psql -c 'create role tudonosso SUPERUSER LOGIN;' postgres
- psql -c 'create database tudonosso_test;' -U tudonosso postgres
- rake db:test:prepare
- sh -e /etc/init.d/xvfb start
env:
- DISPLAY=:99.0
script:
- bundle exec rspec spec
branches:
  only:
  - master
